[package]
name = "piggybank-meta"
version = "0.1.0"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[dependencies.piggybank]
path = ".."

[dependencies.elrond-wasm]
version = "0.23.1"

[dependencies.elrond-wasm-debug]
version = "0.23.1"
